# Generated by Django 3.0.8 on 2020-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='host_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventmember',
            name='status',
            field=models.CharField(choices=[['APP', 'Approved'], ['PND', 'Pending'], ['RJD', 'Rejected']], default='PND', max_length=100),
        ),
    ]
