# Generated by Django 3.0.8 on 2020-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_auto_20200920_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('mem_org', models.CharField(max_length=500)),
                ('tc_pc', models.CharField(max_length=500)),
                ('mo_approval', models.BooleanField(default=False)),
                ('tc_pc_approval', models.BooleanField(default=False)),
                ('fund_support', models.BooleanField()),
                ('add_info', models.TextField()),
            ],
        ),
    ]
