# Generated by Django 3.0.8 on 2020-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_eventform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventform',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
