# Generated by Django 3.0.8 on 2020-09-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20200924_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventform',
            name='form_status',
            field=models.CharField(choices=[['APP', 'Approved'], ['PND', 'Pending'], ['RJD', 'Rejected']], default='PND', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventform',
            name='add_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
