# Generated by Django 3.0.8 on 2020-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_auto_20200925_0946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
        migrations.AddField(
            model_name='eventform',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventMember',
        ),
    ]
