# Generated by Django 3.0.8 on 2020-10-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_auto_20201002_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.EventForm')),
            ],
        ),
    ]
